version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment: 
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - microservices
  graphql-server:
    build:
      context: ./server
    ports:
      - '8080:4000'
    networks:
      - microservices
  react-app-client:
    build:
      context: ./client
    ports:
      - '8000:3000'
    networks:
      - microservices
networks:
  microservices:
volumes:
  my-db: